/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Componentes.Terreno;
import Jugador.Granjero;
import ManejadoresControladores.ManejadorDeCeldas;
import ManejadoresControladores.ManejadorVida;

/**
 *
 * @author Marco Munguia <@markomannder>
 */
public class VentanaTerreno extends javax.swing.JFrame {

    private ManejadorDeCeldas manejadorDeCeldas;
    private Terreno terreno;
    private ManejadorVida manejadorVida;

    /**
     * Creates new form VentanaTerreno
     */
    public VentanaTerreno(Granjero granjero) {
        initComponents();
        this.setTitle("My Littel Farm");
        this.setLocationRelativeTo(null);
        this.terreno = new Terreno();
        manejadorDeCeldas = new ManejadorDeCeldas(terrenoGranjerojPanel, terreno.getCelda());
        nicknameGranjerojLabel.setText(granjero.getNicknameJugador());
        dineroGranjerojLabel.setText(Integer.toString(granjero.getDineroJugador()));
        manejadorVida = new ManejadorVida(vidaGranjerojLabel, granjero, granjero.getVidaJugador(), 2);
        vidaGranjerojLabel.setText(Integer.toString(granjero.getVidaJugador()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        juegoInicialjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inventarioGranjerojPanel = new javax.swing.JPanel();
        imagenMercadojLabel = new javax.swing.JLabel();
        imagenNicknamejLabel = new javax.swing.JLabel();
        imagenVidajLabel = new javax.swing.JLabel();
        dineroGranjerojLabel = new javax.swing.JLabel();
        nicknameGranjerojLabel = new javax.swing.JLabel();
        vidaGranjerojLabel = new javax.swing.JLabel();
        imagenDinerojLabel = new javax.swing.JLabel();
        imagenInventariojLabel = new javax.swing.JLabel();
        inventariojButton = new javax.swing.JButton();
        mercadojButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        terrenoGranjerojPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoJuego.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        inventarioGranjerojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenMercadojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenMercado.png"))); // NOI18N
        inventarioGranjerojPanel.add(imagenMercadojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, 40, 30));

        imagenNicknamejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenNickname.png"))); // NOI18N
        inventarioGranjerojPanel.add(imagenNicknamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        imagenVidajLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenVida.png"))); // NOI18N
        inventarioGranjerojPanel.add(imagenVidajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 30));

        dineroGranjerojLabel.setForeground(new java.awt.Color(0, 0, 0));
        inventarioGranjerojPanel.add(dineroGranjerojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 115, 110, 30));

        nicknameGranjerojLabel.setForeground(new java.awt.Color(0, 0, 0));
        inventarioGranjerojPanel.add(nicknameGranjerojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 20, 110, 30));

        vidaGranjerojLabel.setForeground(new java.awt.Color(0, 0, 0));
        inventarioGranjerojPanel.add(vidaGranjerojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 110, 30));

        imagenDinerojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenDinero.png"))); // NOI18N
        inventarioGranjerojPanel.add(imagenDinerojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 40, 30));

        imagenInventariojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenInventario.png"))); // NOI18N
        inventarioGranjerojPanel.add(imagenInventariojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 30));

        inventariojButton.setBackground(new java.awt.Color(0,0,0,0));
        inventariojButton.setForeground(new java.awt.Color(0, 0, 0));
        inventariojButton.setText("Inventario");
        inventariojButton.setBorder(null);
        inventarioGranjerojPanel.add(inventariojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 160, 90, 30));

        mercadojButton.setBackground(new java.awt.Color(0,0,0,0));
        mercadojButton.setForeground(new java.awt.Color(0, 0, 0));
        mercadojButton.setText("Mercado");
        mercadojButton.setBorder(null);
        inventarioGranjerojPanel.add(mercadojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 205, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInventario Panel.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        inventarioGranjerojPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 171, -1));

        terrenoGranjerojPanel.setBackground(new java.awt.Color(0,0,0,0));
        terrenoGranjerojPanel.setLayout(new java.awt.GridLayout(5, 5, 4, 4));

        javax.swing.GroupLayout juegoInicialjPanelLayout = new javax.swing.GroupLayout(juegoInicialjPanel);
        juegoInicialjPanel.setLayout(juegoInicialjPanelLayout);
        juegoInicialjPanelLayout.setHorizontalGroup(
            juegoInicialjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juegoInicialjPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(inventarioGranjerojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(terrenoGranjerojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        juegoInicialjPanelLayout.setVerticalGroup(
            juegoInicialjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juegoInicialjPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(terrenoGranjerojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
            .addGroup(juegoInicialjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(inventarioGranjerojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(juegoInicialjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(juegoInicialjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dineroGranjerojLabel;
    private javax.swing.JLabel imagenDinerojLabel;
    private javax.swing.JLabel imagenInventariojLabel;
    private javax.swing.JLabel imagenMercadojLabel;
    private javax.swing.JLabel imagenNicknamejLabel;
    private javax.swing.JLabel imagenVidajLabel;
    private javax.swing.JPanel inventarioGranjerojPanel;
    private javax.swing.JButton inventariojButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel juegoInicialjPanel;
    private javax.swing.JButton mercadojButton;
    private javax.swing.JLabel nicknameGranjerojLabel;
    private javax.swing.JPanel terrenoGranjerojPanel;
    private javax.swing.JLabel vidaGranjerojLabel;
    // End of variables declaration//GEN-END:variables
}
